# Generated by Django 4.2 on 2023-05-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shamem2app', '0007_tag_remove_post_location_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='decade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='exact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='season',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='timeline_type',
            field=models.CharField(choices=[('exact_date', 'Exact date'), ('decade', 'Decade'), ('season', 'Season')], default='exact_date', max_length=15),
        ),
    ]
