# Generated by Django 4.2 on 2023-05-14 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shamem2app', '0010_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
