# Generated by Django 4.2 on 2023-05-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shamem2app', '0014_remove_post_location_post_location_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location_name',
        ),
    ]
