# Generated by Django 4.2 on 2023-05-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shamem2app', '0015_delete_tag_remove_post_location_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='old_tags',
        ),
    ]
