# Generated by Django 4.2 on 2023-05-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shamem2app', '0016_rename_tags_post_old_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='old_tags',
            new_name='tags',
        ),
    ]
