# Generated by Django 4.2 on 2023-05-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shamem2app', '0017_rename_old_tags_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
