# Generated by Django 4.2 on 2023-05-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shamem2app', '0019_remove_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
