# Generated by Django 4.1.7 on 2023-04-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/static/images/default.jpg', upload_to='profile_pictures/'),
        ),
    ]
